// dashboard/src/features/cluster/components/ClusterPage.tsx
import { useQuery } from "@tanstack/react-query";
import { Header } from "@/components/layout/Header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api/client";
import { config } from "@/config";
import { formatRelativeTime } from "@/lib/utils";
import type { ClusterNode } from "@/types";
import {
    Server,
    Crown,
    Copy,
    Circle,
    RefreshCw,
    AlertCircle,
    ArrowRight,
} from "lucide-react";

export function ClusterPage() {
    // Fetch cluster nodes
    const nodesQuery = useQuery({
        queryKey: ["cluster-nodes"],
        queryFn: async () => {
            const response = await api.get<{ data: ClusterNode[] }>(
                `${config.endpoints.control}/cluster/nodes`
            );
            if (response.error) throw new Error(response.error.message);
            return response.data?.data || [];
        },
    });

    const authority = nodesQuery.data?.find((n) => n.role === "authority");
    const replicas = nodesQuery.data?.filter((n) => n.role === "replica") || [];

    const getStatusColor = (status: string) => {
        switch (status) {
            case "healthy":
                return "text-green-500 fill-green-500";
            case "degraded":
                return "text-amber-500 fill-amber-500";
            case "offline":
                return "text-red-500 fill-red-500";
            default:
                return "text-[hsl(var(--muted-foreground))]";
        }
    };

    const getStatusBg = (status: string) => {
        switch (status) {
            case "healthy":
                return "border-green-500/50 bg-green-500/5";
            case "degraded":
                return "border-amber-500/50 bg-amber-500/5";
            case "offline":
                return "border-red-500/50 bg-red-500/5";
            default:
                return "";
        }
    };

    return (
        <div className="flex flex-col h-screen">
            <Header
                title="Cluster"
                subtitle="Topology and replication status"
                onRefresh={() => nodesQuery.refetch()}
                isRefreshing={nodesQuery.isFetching}
            />

            <div className="flex-1 p-6 overflow-auto">
                {nodesQuery.isLoading ? (
                    <div className="flex items-center justify-center py-24">
                        <RefreshCw className="h-8 w-8 animate-spin text-[hsl(var(--muted-foreground))]" />
                    </div>
                ) : nodesQuery.error ? (
                    <div className="flex flex-col items-center justify-center py-24 text-[hsl(var(--destructive))]">
                        <AlertCircle className="h-12 w-12 mb-4" />
                        <p>{(nodesQuery.error as Error).message}</p>
                    </div>
                ) : (
                    <div className="space-y-8">
                        {/* Cluster topology visualization */}
                        <Card>
                            <CardHeader>
                                <CardTitle className="text-base">Cluster Topology</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <div className="flex items-center justify-center gap-8 py-8">
                                    {/* Authority node */}
                                    {authority && (
                                        <div
                                            className={`p-6 rounded-xl border-2 ${getStatusBg(
                                                authority.status
                                            )}`}
                                        >
                                            <div className="flex items-center gap-2 mb-3">
                                                <Crown className="h-5 w-5 text-amber-500" />
                                                <span className="font-semibold">Authority</span>
                                            </div>
                                            <div className="flex items-center gap-2 mb-2">
                                                <Server className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
                                                <span className="text-sm font-mono">
                                                    {authority.host}:{authority.port}
                                                </span>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Circle className={`h-3 w-3 ${getStatusColor(authority.status)}`} />
                                                <span className="text-sm capitalize">{authority.status}</span>
                                            </div>
                                        </div>
                                    )}

                                    {/* Replication arrows */}
                                    {replicas.length > 0 && (
                                        <div className="flex flex-col items-center gap-2">
                                            {replicas.map((_, i) => (
                                                <ArrowRight
                                                    key={i}
                                                    className="h-6 w-6 text-[hsl(var(--muted-foreground))]"
                                                />
                                            ))}
                                        </div>
                                    )}

                                    {/* Replica nodes */}
                                    <div className="flex flex-col gap-4">
                                        {replicas.map((replica) => (
                                            <div
                                                key={replica.id}
                                                className={`p-4 rounded-xl border-2 ${getStatusBg(
                                                    replica.status
                                                )}`}
                                            >
                                                <div className="flex items-center gap-2 mb-2">
                                                    <Copy className="h-4 w-4 text-blue-500" />
                                                    <span className="font-medium">Replica</span>
                                                </div>
                                                <div className="flex items-center gap-2 mb-1">
                                                    <Server className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
                                                    <span className="text-sm font-mono">
                                                        {replica.host}:{replica.port}
                                                    </span>
                                                </div>
                                                <div className="flex items-center justify-between">
                                                    <div className="flex items-center gap-2">
                                                        <Circle className={`h-3 w-3 ${getStatusColor(replica.status)}`} />
                                                        <span className="text-sm capitalize">{replica.status}</span>
                                                    </div>
                                                    {replica.lag_ms !== undefined && (
                                                        <span className="text-xs text-[hsl(var(--muted-foreground))]">
                                                            {replica.lag_ms}ms lag
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                        {replicas.length === 0 && (
                                            <div className="p-4 rounded-xl border-2 border-dashed text-[hsl(var(--muted-foreground))]">
                                                <p className="text-sm">No replicas configured</p>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </CardContent>
                        </Card>

                        {/* Node details */}
                        <div className="grid grid-cols-3 gap-4">
                            {nodesQuery.data?.map((node) => (
                                <Card key={node.id}>
                                    <CardHeader className="pb-2">
                                        <div className="flex items-center justify-between">
                                            <CardTitle className="text-sm flex items-center gap-2">
                                                {node.role === "authority" ? (
                                                    <Crown className="h-4 w-4 text-amber-500" />
                                                ) : (
                                                    <Copy className="h-4 w-4 text-blue-500" />
                                                )}
                                                {node.role === "authority" ? "Authority" : "Replica"}
                                            </CardTitle>
                                            <Circle className={`h-3 w-3 ${getStatusColor(node.status)}`} />
                                        </div>
                                    </CardHeader>
                                    <CardContent className="space-y-2 text-sm">
                                        <div className="flex justify-between">
                                            <span className="text-[hsl(var(--muted-foreground))]">Host</span>
                                            <span className="font-mono">{node.host}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-[hsl(var(--muted-foreground))]">Port</span>
                                            <span className="font-mono">{node.port}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-[hsl(var(--muted-foreground))]">Status</span>
                                            <span className="capitalize">{node.status}</span>
                                        </div>
                                        {node.lag_ms !== undefined && (
                                            <div className="flex justify-between">
                                                <span className="text-[hsl(var(--muted-foreground))]">Lag</span>
                                                <span>{node.lag_ms}ms</span>
                                            </div>
                                        )}
                                        <div className="flex justify-between">
                                            <span className="text-[hsl(var(--muted-foreground))]">
                                                Last Heartbeat
                                            </span>
                                            <span>{formatRelativeTime(node.last_heartbeat)}</span>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

// dashboard/src/pages/cluster/ClusterPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query'
import AppLayout from '@/components/layout/AppLayout.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import { useApi } from '@/composables/useApi'
import type { ClusterNode } from '@/types'

const { api } = useApi()
const queryClient = useQueryClient()

const showPromoteDialog = ref(false)
const selectedNode = ref<ClusterNode | null>(null)

// Fetch cluster topology
const { data: topology, isLoading, error, refetch } = useQuery({
  queryKey: ['cluster-topology'],
  queryFn: async () => {
    const { data } = await api!.get('/control/topology')
    return data as { nodes: ClusterNode[] }
  },
})

// Promote replica mutation
const promoteMutation = useMutation({
  mutationFn: async (nodeId: string) => {
    const { data } = await api!.post('/control/promote', { node_id: nodeId })
    return data
  },
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['cluster-topology'] })
    showPromoteDialog.value = false
    selectedNode.value = null
  },
})

const handlePromoteClick = (node: ClusterNode) => {
  selectedNode.value = node
  showPromoteDialog.value = true
}

const confirmPromote = () => {
  if (selectedNode.value) {
    promoteMutation.mutate(selectedNode.value.id)
  }
}

const getStatusColor = (status: string) => {
  return status === 'online' ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'
}

const getRoleColor = (role: string) => {
  return role === 'authority' ? 'bg-blue-500/20 text-blue-400' : 'bg-purple-500/20 text-purple-400'
}
</script>

<template>
  <AppLayout>
    <div class="space-y-6">
      <div class="flex items-center justify-between">
        <h1 class="text-3xl font-bold">Cluster</h1>
        <button
          @click="refetch()"
          class="px-4 py-2 rounded border border-border hover:bg-secondary"
        >
          🔄 Refresh
        </button>
      </div>

      <div v-if="isLoading" class="text-center py-12">
        <p class="text-muted-foreground">Loading cluster topology...</p>
      </div>

      <div v-else-if="error" class="p-4 bg-destructive/10 text-destructive rounded-lg">
        Failed to load topology: {{ error }}
      </div>

      <div v-else-if="!topology || !topology.nodes || topology.nodes.length === 0" class="text-center py-12">
        <p class="text-muted-foreground">No nodes found</p>
      </div>

      <div v-else class="space-y-6">
        <!-- Topology Visualization -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div
            v-for="node in topology.nodes"
            :key="node.id"
            class="p-6 bg-card border border-border rounded-lg"
          >
            <div class="flex items-start justify-between mb-4">
              <div>
                <h3 class="text-lg font-semibold mb-2">{{ node.id }}</h3>
                <div class="flex gap-2">
                  <span :class="['text-xs px-2 py-1 rounded', getRoleColor(node.role)]">
                    {{ node.role }}
                  </span>
                  <span :class="['text-xs px-2 py-1 rounded', getStatusColor(node.status)]">
                    {{ node.status }}
                  </span>
                </div>
              </div>
            </div>

            <div v-if="node.replication_lag !== undefined" class="space-y-2">
              <div class="text-sm text-muted-foreground">
                Replication Lag: <span class="font-mono">{{ node.replication_lag }}ms</span>
              </div>
              <div class="w-full bg-secondary rounded-full h-2">
                <div
                  :class="[
                    'h-2 rounded-full',
                    node.replication_lag < 100 ? 'bg-green-500' :
                    node.replication_lag < 500 ? 'bg-yellow-500' : 'bg-red-500'
                  ]"
                  :style="{ width: `${Math.min((node.replication_lag / 1000) * 100, 100)}%` }"
                ></div>
              </div>
            </div>

            <button
              v-if="node.role === 'replica' && node.status === 'online'"
              @click="handlePromoteClick(node)"
              class="mt-4 w-full px-4 py-2 rounded bg-primary text-primary-foreground hover:opacity-90"
            >
              Promote to Authority
            </button>
          </div>
        </div>

        <!-- Statistics -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div class="p-4 bg-card border border-border rounded-lg">
            <div class="text-sm text-muted-foreground mb-1">Total Nodes</div>
            <div class="text-2xl font-bold">{{ topology.nodes.length }}</div>
          </div>
          
          <div class="p-4 bg-card border border-border rounded-lg">
            <div class="text-sm text-muted-foreground mb-1">Online Nodes</div>
            <div class="text-2xl font-bold text-green-400">
              {{ topology.nodes.filter(n => n.status === 'online').length }}
            </div>
          </div>
          
          <div class="p-4 bg-card border border-border rounded-lg">
            <div class="text-sm text-muted-foreground mb-1">Replicas</div>
            <div class="text-2xl font-bold text-purple-400">
              {{ topology.nodes.filter(n => n.role === 'replica').length }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Promote Confirmation Dialog -->
    <ConfirmDialog
      v-model:open="showPromoteDialog"
      title="Promote Replica to Authority"
      :description="`Are you sure you want to promote ${selectedNode?.id} to authority? This will trigger a failover.`"
      action-label="Promote"
      variant="default"
      @confirm="confirmPromote"
    />
  </AppLayout>
</template>

<style scoped>
</style>
